### ISSUE TITLE
'lodash/clamp' failed to resolve error when start project with limeplay lib

### ISSUE THREAD

**Issue by wevertoonsilva** [WINOFFRG/limeplay#39]
BREAKING CHANGE: The request 'lodash/clamp' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.

**Comment by wevertoonsilva** [comment]
I opened PR to resolve this problem.

**Comment by BaHGet** [comment]
> BREAKING CHANGE: The request 'lodash/clamp' failed to resolve only because it was resolved as fully specified (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '_.mjs' file, or a '_.js' file where the package.json contains '"type": "module"'). The extension in the request is mandatory for it to be fully specified.

still not fixed ?

**Comment by WINOFFRG** [comment]
Fixed in lastest version, Kindly check.
